version: '3'
services:
  api:
    build: './'
    image: ufrn/agendataxi:latest
    container_name: api-taxi
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5000:5000'
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    expose:
      - '8080'
    ports:
      - 8080:8080
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/openapi.yaml
